version: '3'
services:
#mssql docker
    ebotanika-sql:
        image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
        restart: unless-stopped
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=QWElkj132!
            - MSSQL_PID=Developer
        ports:
            - 1401:1433
        expose:
            - 1433
        networks:
            - ebotanikanet

    ebotanika-api:
        restart: unless-stopped
        build: 
          context: .
        environment:
            - ConnectionStrings:DefaultConnection=Server=ebotanika-sql,1433;Database=eBotanika;User=sa;Password=QWElkj132!;ConnectRetryCount=0
            - ASPNETCORE_ENVIRONMENT=Development
        ports:
            - 44363:44363
        networks:
            - ebotanikanet
        links:
            - ebotanika-sql 
        depends_on:
            - ebotanika-sql
        

networks:
  ebotanikanet:
    driver: bridge