version: "3"
services:
    ebotanika-sql:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        restart: unless-stopped
        environment:
            SA_PASSWORD: "QWElkj132!"
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Developer"
        ports:
            - 1433:1433
        networks:
            - ebotanikanet

    ebotanika-api:
        restart: unless-stopped
        build: .
        environment:
            - ConnectionStrings:eBotanika=Server=ebotanikasql,1433;Database=eBotanika;User=sa;Password=QWElkj132!;
        ports:
            - 5000:80
        networks:
            - ebotanikanet
        depends_on:
            - ebotanika-sql
        links:
            - ebotanika-sql 

networks:
  ebotanikanet
    driver: bridge